name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build backend image
      run: docker build -t backend:v1 ./backend

    - name: Build frontend image
      run: docker build -t frontend:v1 ./app
